### ISSUE TITLE
Ubuntu 16.04

### ISSUE THREAD

**Issue by ddavidebor** [Microsoft/microsoft-r-open#1]
Is support for Ubuntu 16.04 LTS to be expected soon?

**Comment by nathansoz** [comment]
Hi @ddavidebor. While I can't comment on if/when the OS will officially be on the "supported list," there shouldn't be any *technical* reason why the installer/packages would not work on Ubuntu 16.04. My main Linux development workstation is Ubuntu 16.04 and installs/runs just fine.
