### ISSUE TITLE
MRAN is down

### ISSUE THREAD

**Issue by shosaco** [Microsoft/microsoft-r-open#103]
[https://mran.microsoft.com/timemachine](https://mran.microsoft.com/timemachine) dows not work. Noticed while building a docker image. Also not possible to use the R checkpoint package at the moment.

**Comment by maxheld83** [comment]
can confirm this, e.g.:

```
> install.packages("ggplot2")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository https://mran.microsoft.com/snapshot/2019-03-14/src/contrib:
  cannot open URL 'https://mran.microsoft.com/snapshot/2019-03-14/src/contrib/PACKAGES'
Warning message:
package ‘ggplot2’ is not available (for R version 3.5.2)
```

also see: https://twitter.com/maxheld/status/1168911398904221696

Have also emailed `mran@microsoft.com` and referenced this issue.

**Comment by maxheld83** [comment]
it's being looked into.

**Comment by eturkes** [comment]
Seems to be back up. Just installed a package and https://mran.microsoft.com/timemachine loads.

**Comment by maxheld83** [comment]
https://twitter.com/revodavid/status/1168920608014553094

**Comment by rsmith54** [comment]
It is still not working for me.

**Comment by eturkes** [comment]
Yes, I take back my comment. It seems to be working only intermittently.

**Comment by maxheld83** [comment]
down again for me as well, on several machines and networks.

**Comment by patr1ckm** [comment]
Still down for me

**Comment by jeroenterheerdt** [comment]
Just wanted to let you know that we are aware of this and are actively working on it. Please do not open any more issues.

**Comment by rsmith54** [comment]
Is there somewhere to look for status updates? This is still down for me.

**Comment by shosaco** [comment]
> Just wanted to let you know that we are aware of this and are actively working on it. Please do not open any more issues.

If you are closing this issue, it disappears from the standard Github Isssue filter, causing more people to open an issue. If you left it open, people would see it and refrain from opening another one. Also, closing an issue while the issue is not resolved seems odd :-)

Thanks for your support!
