### ISSUE TITLE
MRAN Shapshot is down

### ISSUE THREAD

**Issue by lucasveljacic** [Microsoft/microsoft-r-open#104]
Hello, 
I don't know if this is the place to make this kind of comments. If it doesn't, I'm sorry, I don't know where else to do it.

I'm getting `server error 502` when trying to install a package from a snapshot since yesterday. 

Here an example: 
```
install.packages("prophet", repos = "https://mran.microsoft.com/snapshot/2018-11-01")
```

```
$ wget https://mran.microsoft.com/snapshot/2018-11-01/src/contrib/PACKAGES
2019-09-03 18:23:24  https://mran.microsoft.com/snapshot/2018-11-01/src/contrib/PACKAGES
Resolving mran.microsoft.com (mran.microsoft.com)... 40.118.246.51
Connecting to mran.microsoft.com (mran.microsoft.com)|40.118.246.51|:443... connected.
HTTP request sent, awaiting response... 502 Bad Gateway
2019-09-03 18:24:07 ERROR 502: Bad Gateway.
```

Is there an ETA for the solution. 
I use your great service to provision some machines in its start up time in a predictable way.

Thanks!

**Comment by hartywillis** [comment]
Down for us too - this is a huge blocker for us!

**Comment by nir4most** [comment]
its affecting many people:
https://social.msdn.microsoft.com/Forums/en-US/e7db8c6e-3dad-4248-b9c3-79f4bb499b76/cannot-install-any-packages-from-mran

**Comment by f0nzie** [comment]
It is down in Houston as well.

**Comment by LucianoGandini** [comment]
It is down in Argentina as well.

**Comment by f0nzie** [comment]
https://mran.microsoft.com/timemachine

![image](https://user-images.githubusercontent.com/29108853/64263122-c1c89180-cef4-11e9-82ee-65c45e899917.png)

**Comment by stonilee** [comment]
Still no luck today. Hopefully this gets resolved or a workaround is posted.

**Comment by nir4most** [comment]
it would be wonderful if there was an MRAN mirror somewhere to act as a redundancy...

**Comment by lucasveljacic** [comment]
It's back again.
An MRAN mirror suggested by @nir4most would be great!

Thanks for the support.
