### ISSUE TITLE
MRAN appears to be down

### ISSUE THREAD

**Issue by marcelo-g-simas** [Microsoft/microsoft-r-open#117]
Just got this error while trying to build a container:

```
 Warning: unable to access index for repository https://mran.microsoft.com/snapshot/2019-12-12/src/contrib:
  cannot open URL 'https://mran.microsoft.com/snapshot/2019-12-12/src/contrib/PACKAGES'
```

**Comment by rsmith54** [comment]
Yes, MRAN seems to be down again.

**Comment by alexvorobiev** [comment]
We are looking at the new RStudio public package manager as a backup. For instance this is the URL for the 12/18/1999 snapshot:
```
"https://packagemanager.rstudio.com/all/238"
```

**Comment by ahalbert** [comment]
I am unable to use it either

**Comment by marcelo-g-simas** [comment]
It appears to be back up, we will stop using it.  Just learned today that rocker/verse base containers were using MRAN.  I've switched to use an internal CRAN mirror we have setup for the company.
