### ISSUE TITLE
when install mro on windows, some pc will automatically rollback

### ISSUE THREAD

**Issue by alitrack** [Microsoft/microsoft-r-open#14]
just rollback without error log.

but it works if I copy the full folder to the pc has issue.

**Comment by nathansoz** [comment]
Please try to reproduce by running:

msiexec /i <name-of-msi>.msi /l*v log.txt

This will output a log that you can attach to this issue.

**Comment by alitrack** [comment]
here is the log, thanks in advance.
[mro.zip](https://github.com/Microsoft/microsoft-r-open/files/585013/mro.zip)

**Comment by nathansoz** [comment]
I see that it is failing in the section where we try to retrieve/install the MKL. Does the computer in question have an internet connection?

**Comment by alitrack** [comment]
could you tell me where to download MKL, can access website, but have no idea if MKL is blocked by GFW or some other issues.

**Comment by nathansoz** [comment]
Sorry for the late reply. Your OS wouldn't happen to be Windows 7, would it? If so, do you have .NET framework 4.5.1 installed?

**Comment by alitrack** [comment]
Windows 2008 R2 with SP1

still failed after install .NET framework 4.6.2

**Comment by nathansoz** [comment]
I've asked someone on our team to try to repro this.
