### ISSUE TITLE
 libpng12.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by alitrack** [Microsoft/microsoft-r-open#15]
```
unable to load shared object '/usr/lib64/microsoft-r/3.3/lib64/R/modules//R_X11.so':
  libpng12.so.0: cannot open shared object file: No such file or directory
```
debian test version
solution, 
it has libpng16.so.0
so I tried 
```
ln -s /usr/lib/x86_64-linux-gnu/libpng.so /usr/lib64/microsoft-r/3.3/lib64/R/lib/libpng12.so.0
```
and it works

**Comment by nathansoz** [comment]
Can you install libpng12-0 package on the latest version of debian? Please not that debian is not an officially supported distribution.

**Comment by alitrack** [comment]
I can install libpng12-0, but it will remove libpng16-0
I install mro in rocker/rstudio, and it bases on testing version debian.
Of course I can create a Dockerfile with an officially supported distribution,

**Comment by nathansoz** [comment]
We will be looking at fixing this for 3.3.3 as it also blocks Ubuntu 16.10. For now, I would use a supported distribution.
