### ISSUE TITLE
Registry key 'SOFTWARE\Revolution' not found

### ISSUE THREAD

**Issue by alitrack** [Microsoft/microsoft-r-open#16]
on Windows, when I ran 

```r
Windows = findRscript(version = "3.3.1.*x64" )
```

I got the following error message,

```
Error in readRegistry(ptn, maxdepth = 3) : 
  Registry key 'SOFTWARE\Revolution' not found
```

**Comment by nathansoz** [comment]
This looks like an issue with findRscript.R and not Microsoft R Open. You may want to comment there and have them remove the reference to SOFTWARE\Revolution.

https://github.com/andrie/version.compare/blob/master/R/findRscript.R
