### ISSUE TITLE
Failed to compile Rcpp based packages

### ISSUE THREAD

**Issue by yzhao0527** [Microsoft/microsoft-r-open#17]
I couldn't compile Rcpp-based package `RcppBDT` on two of my PCs, one uses CentOS and the other uses Ubuntu.  The errors are the same. (I can compile some other Rcpp-based packages though)

Here's the link to the original post:  https://github.com/eddelbuettel/rcppbdt/issues/3

The problem is weird.  R is supposed to compile c++ source scripts with something like

    g++ -I/usr/lib64/microsoft-r/3.3/include ...

However, it removed the first part of the above command and run the following instead

    I/user/lib64/microsoft-r/3.3/include ...

Then I got a No File Found error, because there's no file named `I/user/lib64/microsoft-r/3.3/include`

**Comment by nathansoz** [comment]
This is related to #11 and is a side effect of how we compile microsoft-r-open. A temporary workaround is to download the package source and edit: src/Makevars

Remove:

## We want C++11 as it gets us 'long long' as well
CXX_STD = CXX11

And then edit the PKG_CPPFLAGS line to looks like this:

PKG_CPPFLAGS = -I../inst/include/ -std=c++11

**Comment by eddelbuettel** [comment]
Thanks for the follow-up, and the reference!  I left a message in their https://github.com/Microsoft/microsoft-r-open/issues/11 thread too.

**Comment by nathansoz** [comment]
As far as I know, there is no "default compiler" for R on Linux (whereas I know there is a specified toolchain for Windows that we use). Can you point me to documentation that specifies a default compiler for R on Linux?

**Comment by eddelbuettel** [comment]
>  there is no "default compiler" for R on Linux 

You have the question backwards:

```bash
tar xfz R_*tar.gz  # some release
configure       # lots of options
make
make install
```

will work with just about any compiler version -- that is what `configure`.

BUT that compiler version and its capabilities are then encoded.  

You play a risky game by messing.   You can, however, override with a suitable set of arguments in the system `Makeconf` or a level above (via env.vars). It is doable, but a ton of things may break and you get to pick up the pieces.  Just test this real well.
