### ISSUE TITLE
Issues with MKL when installing Microsoft R Open

### ISSUE THREAD

**Issue by IrenevandeLinde** [Microsoft/microsoft-r-open#18]
My companies IT department installed Microsoft R Open 3.3.1 for me. However, when opening R studio and selecting Microsoft R Open I receive the following comment in the console;
No performance acceleration libraries were detected. To take advantage of 
the available processing power, also install MKL for R Open. 

So I checked with my IT department and they let me know the following;
While installing the given source we got the following error (Proxy Authentication Error - 407) and the error was caused by the MKL library that has been embedded with the source that we were provided . On research we came to know that MKL is a library by Intel to accelerate performance , so we disabled the library installation to prevent this error.

Is there anyone here that can help me with this issue?
Thanks!

**Comment by ddavidebor** [comment]
It seems to me your IT got stuck behind their own proxy
