### ISSUE TITLE
Error message from foreach+doParallel loop

### ISSUE THREAD

**Issue by giantwhale** [Microsoft/microsoft-r-open#19]
I typically parallelize my code as follows:

    cl <- makeCluster(20, outfile='log.txt')
    registerDoParallel(cl)
    foreach(x=some_vectro) %dopar% {
        # time consuming processes
    }

The process usually succeeds, however, when I check the log file, I usually see the following at the end of the file:

    Error in unserialize(node$con) : error reading from connection
    Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
    Execution halted

This is reproducible on my PC.  Does this hint something is wrong? how can I find out where things went wrong?

**Comment by nathansoz** [comment]
@richcalaway might be able to answer your question. Let me see if I can get him on this thread.

**Comment by hai-dang-dau** [comment]
Here is a reproducible example:

library(parallel)

N <- 1e6
# N <- 5000 works fine on my computer. N <- 10000 already creates error.
X <- matrix(rnorm(N), ncol = 2)
cl <- makeForkCluster(nnodes = 2)
f <- function(i) X %*% matrix(c(1, 1), ncol = 1)
Y <- parLapply(cl, 1:3, f)

**Comment by richcalaway** [comment]
This last  example does not use foreach/doParallel; parLapply is a straight call into the parallel package, so does not reproduce the original complaint. For what it's worth, it does not reproduce on my CentOS 7 development machine as written. Again, unless the return value is not what is expected, the existence of such messages in the log does not necessarily indicate a problem.
