### ISSUE TITLE
Download url accessible by script

### ISSUE THREAD

**Issue by ddavidebor** [Microsoft/microsoft-r-open#2]
We frequently deploy R studio server VMs and have some build script to do that.

I'd like to move them over to Microsoft R open.

I've noticed you haven't published the release files on github, also the parent directories on your webserver, for example `https://mran.microsoft.com/install/mro/` return a 403 forbidden error.

Do you have a way to always get the url of the latest stable release? (apart from webscaping)

**Comment by nathansoz** [comment]
This probably won't happen before our next release, but I believe there are plans to host debian and rpm repositories that I think will do much of what you want. If and when we do this, I'll be sure to include a /latest directory that will point to latest stable.
