### ISSUE TITLE
OSX package ‘RevoUtilsMath’ is not available (for R version 3.4.0)

### ISSUE THREAD

**Issue by sefabey** [Microsoft/microsoft-r-open#28]
I've installed R from Mran and tried to check if it's actually running multi-threaded as instructed here https://mran.microsoft.com/documents/rro/multithread/#mt-setget. 

First, I tried to run getMKLthreads() command and it could not find the function. 
Next, I tried installing RevoUtilsMath package (which should have been come installed with Mran I guess) but I got the error in the title. 

Running on OSX Sierra.

**Comment by richcalaway** [comment]
On OSX, we do not provide RevoUtilsMath or the MKL libraries (and control functions) as that OS provides its own Accelerate framework for multi-threaded computation.
