### ISSUE TITLE
vanilla xubuntu 16.04

### ISSUE THREAD

**Issue by flopflip** [Microsoft/microsoft-r-open#3]
runnig install script install.sh produces error on line 28, unexpected "}"

**Comment by nathansoz** [comment]
Can you tell me what "ls -la /bin/bash" looks like? I'm wondering if xubuntu points to a different interpreter in place of bash, which is something I know they have done with /bin/sh on Ubuntu. The code in question (lines 26-28) looks like this:

```bash```
function error {
  echo -e "$*" >&2
}
```

It seems to be a valid bash function to me.

**Comment by nathansoz** [comment]
Closing due to lack of customer response.
