### ISSUE TITLE
Installation complete, but fail to start R

### ISSUE THREAD

**Issue by mushthofa** [Microsoft/microsoft-r-open#30]
I previously installed MRO with MKL on my Ubuntu 17.04. I then removed it, and now I wanted to install it again. I encounter the problem in the previously-reported issue: https://github.com/Microsoft/microsoft-r-open/issues/21 , but I could then install by force-removing the previous installation and removing the folder /usr/lib64/microsoft-r/3.4. So, then the installation went without any trouble, but when I try to start R, I get: 

```
R version 3.4.0 (2017-04-21) -- "You Stupid Darkness"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
....
caught segfault ***
address 0x38, cause 'memory not mapped'

Traceback:

 1: dyn.load(libPath)
 2: doTryCatch(return(expr), name, parentenv, handler)
 3: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 4: tryCatchList(expr, classes, parentenv, handlers)
...
(long messages)
...
Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection: 2

```

Removing and reinstalling doesn't help. Any advice?

**Comment by mushthofa** [comment]
If I uninstall MKL, and only install MRO and foreachiterators, R runs, but of course without performance enhancement. As soon as I install MKL, I get the problem again.
BTW, without MKL, I also receive a warning: 
```
In doTryCatch(return(expr), name, parentenv, handler) :
  unable to load shared object '/usr/lib64/microsoft-r/3.4/lib64/R/modules//R_X11.so':
  libpng12.so.0: cannot open shared object file: No such file or directory

```

**Comment by richardborder** [comment]
I have the exact same issue, running under Ubuntu 17.04

**Comment by richardborder** [comment]
Correction--I /had/ this issue but solved it via

```
sudo ln -s libudev.so /lib/x86_64-linux-gnu/libudev.so.0
sudo ln -s libpng16.so /usr/lib/x86_64-linux-gnu/libpng12.so.0
```

as per https://askubuntu.com/questions/838965/where-can-i-find-package-libpng12-so-0

**Comment by scottstanfield** [comment]
Same here. Upgraded from 16.04 to 17.04 (server version)
Removed MRAN 3.3 per instructions
Installed MRAN 3.4
R fails to launch (coredump) due to missing libpng12.so.0

Workaround:
```
cd /usr/lib/x86_64-linux-gnu
sudo ln -s libpng16.so.16 /usr/lib/x86_64-linux-gnu/libpng12.so.0
```

What a headache. I can't believe this fixed it.

**Comment by scottstanfield** [comment]
_Your future self will thank you_

I just ran in to this same problem...Googled it, hit the page, read the last comment...then realized I wrote it just 3 months ago. It still works. So, *thank you, past-self*

Also, you can see what, if any, `libpng` packages you have with `ldconfig -p | grep libpng`.

**Comment by mushthofa** [comment]
@scottstanfield : I wonder if at this point you should just bookmark this page :grin:

**Comment by scottstanfield** [comment]
I thought of that: I could star or follow this page. But I think if I spent a lot of time researching cicadas, I would mentally wire this crazy R core dump to the this horrible but cute little creature...then I'd remember to search for "Stanfield Cicada". 

Ironically, this has triggered another thing I can't seem to remember: the ordering of `ln` parameters. It seems I get dyslexic with the ordering.

**Comment by scottstanfield** [comment]
Ran into this again. It's August 28, 2018. I remembered the Google search term `stanfield cicada` which brought me right back here.

Steps to repro on Ubuntu 18.04

```
wget https://mran.blob.core.windows.net/install/mro/3.5.1/microsoft-r-open-3.5.1.tar.gz
tar xvf $_
cd microsoft-r-open
sudo ./install.sh --accept-mkl-eula --unattended
R
[core ignominiously dumped]
```

And since the last post, I actually *work* for Microsoft now, so maybe I can get this fixed. It'll be the hill I die on.

**Comment by jeroenterheerdt** [comment]
For what is worth, there is a note on the (MRO installation page)[https://mran.microsoft.com/documents/rro/installation] about it:

> On Ubuntu 18.04, you must also install libpng12 from the Linux Kernel archives, as it is no longer part of the Ubuntu distribution, as follows:
```
wget https://mirrors.kernel.org/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1_amd64.deb
dpkg -i libpng12-01_1.2.54-1ubuntu1_amd64.deb
```

**Comment by scottstanfield** [comment]
Under clean install of server-based Ubuntu 19.04 (kernel 5.0) with MRAN 3.5.3 "Great Truth" install successful but R fails to run due to a similar missing library. 

```
% R
/opt/microsoft/ropen/3.5.3/lib64/R/bin/exec/R: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
```

Workaround:
```
cd /usr/lib/x86_64-linux-gnu
sudo ln -s libtinfo.so.6 libtinfo.so.5
```

Curious as to where the reference to `libtinfo` is coming from (it's a low-level terminal library for ncurses):

```
moana lib64/R/lib » pwd
/opt/microsoft/ropen/3.5.3/lib64/R/lib
moana lib64/R/lib » ldd libR.so
        [snip]
        libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007fb235876000)
moana lib64/R/lib »
```

**Comment by scottstanfield** [comment]
Opened a new issue #102 since this is related to `libtinfo.so.5` instead of the `libpng`

**Comment by scottstanfield** [comment]
Found it again, but had to search for cicada stanfield in github.com/search
