### ISSUE TITLE
read.dbf() unable to open DBF file

### ISSUE THREAD

**Issue by ursusfelis** [Microsoft/microsoft-r-open#31]
Error in read.dbf() :  unable to open DBF file

read.dbf() under foreign library doesn´t open DBF File. meanwhile RStudio and RGUI both can open DBF File with same command

I am using Microsoft R Open in Visual Studio Community 2017. with R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"

Simply don't want to open DBF File or it's a issue?

thanks

**Comment by jeroenterheerdt** [comment]
do you happen to have some insight into what type of DBF file you are trying to read? Assuming it is a dBase file? I don't have any at hand but would like to help to reproduce this, if you are still having trouble.

**Comment by zurymarroquin** [comment]
Hello! I am having trouble with this same problem and could really use some help! I downloaded my dbf file from here: https://www.huduser.gov/portal/datasets/assthsg/statedata98/hud4file.zip. This dbf contains names of columns that I am trying to append to another file. However, I can't even open the dbf.
