### ISSUE TITLE
Link to Microsoft R Open 3.4.1 is broken

### ISSUE THREAD

**Issue by skanskan** [Microsoft/microsoft-r-open#36]
Hello.

I've tried to download Microsoft R Open 3.4.1for Windows but the link doesn't work.
https://mran.microsoft.com/install/mro/3.4.1/microsoft-r-open-3.4.1.exe

The link to linux versions doesn't work either.

**Comment by Neil-Schneider** [comment]
It has been almost 2 months since R 3.4.1 was released. Any update on when MRO 3.4.1 will be available?

**Comment by j-martens** [comment]
I believe it will be at the end of the month.

**Comment by Neil-Schneider** [comment]
Thanks!

**Comment by colinfang** [comment]
I think we can close it as the link is changed to

https://mran.blob.core.windows.net/install/mro/3.4.1/microsoft-r-open-3.4.1.tar.gz
