### ISSUE TITLE
3.4 install failure, can not uninstall MKL

### ISSUE THREAD

**Issue by cReedHranac** [Microsoft/microsoft-r-open#38]
I have been attempting to install the 3.4.0 on my Ubuntu 16.04 system and am having errors mainly tracing back to the MKL package it appears. I can not uninstall as described in the documentation [https://mran.microsoft.com/documents/rro/installation/#tab-X1jJ9Wh74-1](url) , and attempted the piece-wise uninstall like described in #10 and it seems similar to #21 . I can not find a way to uninstall. Any suggestions?
 
The MKL log reads:
`Selecting previously unselected package microsoft-r-open-mkl-3.4.
(Reading database ... 230227 files and directories currently installed.)
Preparing to unpack .../microsoft-r-open-mkl-3.4.deb ...
mv: cannot stat '/usr/lib64/microsoft-r/3.4/lib64/R/backup/lib/*.so': No such file or directory
dpkg: warning: subprocess old pre-removal script returned error exit status 1
dpkg: trying script from the new package instead ...
rm: cannot remove '/usr/lib64/microsoft-r/3.4/lib64/R/lib/*.so': No such file or directory
mv: cannot stat '/usr/lib64/microsoft-r/3.4/lib64/R/backup/lib/*.so': No such file or directory
dpkg: error processing archive /home/reed/Downloads/microsoft-r-open/deb/microsoft-r-open-mkl-3.4.deb (--install):
 subprocess new pre-removal script returned error exit status 1
mv: cannot stat '/usr/lib64/microsoft-r/3.4/lib64/R/lib/*.so': No such file or directory
cp: cannot stat '/usr/lib64/microsoft-r/3.4/lib64/R/backup/lib/libR.so': No such file or directory
cp: cannot stat '/usr/lib64/microsoft-r/3.4/stage/Linux/bin/x64/*.so': No such file or directory
dpkg: error while cleaning up:
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 /home/reed/Downloads/microsoft-r-open/deb/microsoft-r-open-mkl-3.4.deb`

**Comment by hugokoopmans** [comment]
same here...

**Comment by hugokoopmans** [comment]
extually I am in even more trouble now, cannot uninstall grrrr
```
 sudo dpkg --remove --force-remove-reinstreq microsoft-r-open-mkl-3.4
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: package is in a very bad inconsistent state; you should
 reinstall it before attempting a removal
(Reading database ... 194918 files and directories currently installed.)
Removing microsoft-r-open-mkl-3.4 (3.4.0) ...
rm: cannot remove '/usr/lib64/microsoft-r/3.4/lib64/R/lib/*.so': No such file or directory
mv: cannot stat '/usr/lib64/microsoft-r/3.4/lib64/R/backup/lib/*.so': No such file or directory
dpkg: error processing package microsoft-r-open-mkl-3.4 (--remove):
 subprocess installed pre-removal script returned error exit status 1
mv: cannot stat '/usr/lib64/microsoft-r/3.4/lib64/R/lib/*.so': No such file or directory
cp: cannot stat '/usr/lib64/microsoft-r/3.4/lib64/R/backup/lib/libR.so': No such file or directory
cp: cannot stat '/usr/lib64/microsoft-r/3.4/stage/Linux/bin/x64/*.so': No such file or directory
dpkg: error while cleaning up:
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 microsoft-r-open-mkl-3.4
```
