### ISSUE TITLE
Package limSolve does not install with MKL on CentOS 7

### ISSUE THREAD

**Issue by clintidau** [Microsoft/microsoft-r-open#4]
The MKL file libRblas.so is missing the fortran symbol "lsame_" which prevents installation of the R package limSolve. It works if I use MRO without MKL because the lsame_ symbol is present in the default libRblas.so

**Comment by nathansoz** [comment]
Hi @clintidau. I was able to reproduce this issue and was also able to modify our build of the Intel MKL to export the lsame_ symbol.

This probably doesn't meet our bar for patching the current release, but it can certainly make it into our next release. However, if you email me at nsosnov "at" microsoft "dot" com I can provide you with the (unsupported) patched binary to ensure that the package actually works for your use case.

**Comment by clintidau** [comment]
Thanks @nathansoz, that fixed the problem for me.

**Comment by nathansoz** [comment]
I'm going to reopen this for tracking purposes.

**Comment by nathansoz** [comment]
MRO 3.3.2 now has lsame symbol. We will be releasing MRO 3.3.2 sometime in November.:

redacted@redacted:/usr/lib64/microsoft-r/3.3/lib64/R/lib> nm libRblas.so | grep same
00000000000d57a0 T lsame
00000000000d57a0 T lsame_
000000000122f9d0 T mkl_serv_lsame
