### ISSUE TITLE
3.4.1 installation fails if other versions of MRO exist

### ISSUE THREAD

**Issue by nicholaelaw** [Microsoft/microsoft-r-open#40]
Just ran into a strange problem here. The 3.4.1 installer fails when the installation is almost finished. Looking through the logs reveals that the installer encountered an error when trying to remove a previous MRO installation. But at this point, the 3.4.1 is already installed and usable, while the previous version has already been removed. 

Removing previous installation(s) manually before commencing produces no error.

The previous versions mentioned above are MRO 3.3.3 and MRO 3.4.0. Which leads to my other question: why would MRO start messing with previous versions? Shouldn't it just leave them as they are, instead of trying to 'upgrade' an older version?

Logs attached:
[MRO_3.4.1_20170914093034.zip](https://github.com/Microsoft/microsoft-r-open/files/1301504/MRO_3.4.1_20170914093034.zip)

**Comment by david-jankoski** [comment]
Had the same experience, however deleting all previous versions did not help resolve the issue. trying to install 3.4.1 failed, removed all previous versions as well. Removed all MRO's and tried again but install is still failing. attached the logs as well in case it helps. thanks

[MRO-3.4.1_inst_fail_logs.zip](https://github.com/Microsoft/microsoft-r-open/files/1310314/MRO-3.4.1_inst_fail_logs.zip)
