### ISSUE TITLE
Why does the R-Open 3.4.1 installer remove prior versions?

### ISSUE THREAD

**Issue by Neil-Schneider** [Microsoft/microsoft-r-open#41]
@nicholaelaw brought this up in #40, but I felt like it should have it's own issue.

I know I had a working environment with the loaded packages and the packages I built myself in 3.4.0. Now if something fails to work in 3.4.1, I no longer have the option to quickly switch back to 3.4.0.

Help us understand why this is necessary or please consider adding an option to the installer to not remove prior installations.

Thanks,

**Comment by nicholaelaw** [comment]
Not to mention this forced upgrade is what caused #40, or so it seems. Why indeed look for trouble when everything was working fine?

**Comment by david-jankoski** [comment]
Just experienced the same - MRO 3.4.1 failed to install **and** it deleted my previous installed version ?!? no questions asked during install procedure...I believe a lot of users have the need to have more than 1 version installed at the same time and would appreciate at least an option to do this during the install process.

**Comment by richcalaway** [comment]
This has been fixed in MRO 3.4.1R2 and later
