### ISSUE TITLE
libpng12.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by whositwhatnow** [Microsoft/microsoft-r-open#44]
I have ropen 3.4.1 installed and for some reason it is not recognizing the shared library file.  I've tried adding a symlink but that doesn't fix the issue.  Im running centos7.

ERROR:

 *** caught segfault ***
address 0x50, cause 'memory not mapped'

Traceback:
 1: dyn.load(libPath)
 2: doTryCatch(return(expr), name, parentenv, handler)
 3: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 4: tryCatchList(expr, classes, parentenv, handlers)

Warning message:
In doTryCatch(return(expr), name, parentenv, handler) :
  unable to load shared object '/cm/shared/apps/R/Microsoft/3.4.1/ropen/3.4.1/lib64/R/modules//R_X11.so':
  libpng12.so.0: cannot open shared object file: No such file or directory

**Comment by jeroenterheerdt** [comment]
Have your tried upgrading to the latest version already?

**Comment by jeroenterheerdt** [comment]
See https://github.com/Microsoft/microsoft-r-open/issues/34#issuecomment-454150159
