### ISSUE TITLE
MRAN CRAN Snapshots are Down

### ISSUE THREAD

**Issue by benjaminrobinson** [Microsoft/microsoft-r-open#48]
Looks like MRAN is down...
https://mran.microsoft.com/documents/rro/reproducibility%23snapshots

**Comment by smithja0423** [comment]
I'm also having difficulty installing packages that were working fine in the very recent past. I opened a thread at the MRO forum.

**Comment by mhines-usgs** [comment]
I'm also having problems getting packages that were fine 19 days ago.. https://travis-ci.org/USGS-R/repgen/builds/304907030?utm_source=github_status&utm_medium=notification

The last time this happened, it was this:
https://github.com/Microsoft/microsoft-r-open/issues/32#issuecomment-311718264
