### ISSUE TITLE
Create repositories for install to replace the package download/install script mechanism

### ISSUE THREAD

**Issue by nathansoz** [Microsoft/microsoft-r-open#5]
This will address #2 and #3

**Comment by nzbart** [comment]
Windows now has some nice command-line installation tools available, including Chocolatey (and hopefully OneGet soon). It would be nice to be able to install Microsoft R in our automated install scripts rather than CRAN R.

For reference, the Chocolatey package for CRAN R is here:
    [The R Project for Statistical Computing](https://chocolatey.org/packages/R.Project)

**Comment by ddavidebor** [comment]
Please use some modern and standardized tool like bintray, so we can have a reliable repository for years ahead.
