### ISSUE TITLE
unable to load shared object R_X11.so

### ISSUE THREAD

**Issue by ShixiangWang** [Microsoft/microsoft-r-open#60]
Anaconda use MRO as default R repository now,  after I install R using Conda and open R, always get warning.

```
Warning message:
In doTryCatch(return(expr), name, parentenv, handler) :
  unable to load shared object '/public/home/liuxs/anaconda3/lib/R/modules//R_X11.so':
  /public/home/liuxs/anaconda3/lib/R/modules//../.././libharfbuzz.so.0: undefined symbol: g_unichar_decompose
R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree"
Platform: x86_64-pc-linux-gnu (64-bit)
```

https://github.com/RevolutionAnalytics/RRO/issues/312 says
>After download and install XQuartz from its website (https://www.xquartz.org), this warning message disappeared.

But I dont how to install this on CentOS 6 and I have no root permission.

**Comment by istevenshen** [comment]
I got the same problem on my CentOS 6 server.

**Comment by manchansan** [comment]
This warning stops me from running conda R inside Jupyter.  Urgently needs this problem fixed.

**Comment by patrickr81** [comment]
I'm having this problem after installation on Debian 9, but with:
In doTryCatch(return(expr), name, parentenv, handler) :
  unable to load shared object '/opt/microsoft/ropen/3.4.4/lib64/R/modules//R_X11.so':
  libpng12.so.0: cannot open shared object file: No such file or directory

**Comment by DataVictorEngineer** [comment]
I encounter the same issue in my JupyterLab, I couldn't run the R codes in notebooks.

The error:
                   could not load anaconda3/lib/R/modules//R_X11.so
                   could not load library /usr/lib/libXt.so.6

I have solved this issue on Centos 7 by installing the:  **sudo yum install libXt**

source: https://altlinux.pkgs.org/sisyphus/classic-i586/libXt-1.1.4-alt1.i586.rpm.html

**Comment by jeroenterheerdt** [comment]
See https://github.com/Microsoft/microsoft-r-open/issues/34#issuecomment-454150159.
