### ISSUE TITLE
Question: Citrix / Terminal Services support for Microsoft R Open?

### ISSUE THREAD

**Issue by jwbowers** [Microsoft/microsoft-r-open#61]
Hi All,

We are having trouble installing and running ordinary R in a Citrix environment for use over Microsoft Terminal Services/RDS"Remote Desktop Services"/HDX"High Definition Experience". Is this something that is supported by Microsoft R Open?

Thanks!

Jake

**Comment by jeroenterheerdt** [comment]
What would be the platform you are planning to install MRO on?
