### ISSUE TITLE
Publish MRO to Windows Store for Windows 10 S

### ISSUE THREAD

**Issue by WenqiangXie** [Microsoft/microsoft-r-open#65]
Could be published MRO to Windows Store? I have a device with Windows 10 S, and I want use MRO in that device, but Windows 10 S just get software from Windows Store. Now have much win32 software published to store, so it's will be nice if we can get MRO from Windows Store.

**Comment by richcalaway** [comment]
Sorry, we have no such plans at this time. MRO is a 64-bit application, so currently can't be made to work in Windows 10 S.
