### ISSUE TITLE
ggplot2 is not loading- MRO 3.5.0

### ISSUE THREAD

**Issue by saifsikdar** [Microsoft/microsoft-r-open#68]
Hi,

I installed MRO latest version 3.5.0 and linked with RStudio.  Then, I installed a number of packages.  However,  ggplot2 was not loaded and the error message says that ggplot2 is built for R3.5.1
Could you please let me know how to update MRO to 3.5.1 version compatible?

Thanks,

Saif

**Comment by richcalaway** [comment]
[MRO 3.5.1](https://mran.microsoft.com/download) is now available.
