### ISSUE TITLE
Install MRO with MKL on Fedora

### ISSUE THREAD

**Issue by waynelapierre** [Microsoft/microsoft-r-open#73]
How can I install Microsoft R Open with MKL on Fedora? Are there any extra steps needed besides the installation instructions provided in your website?

**Comment by jeroenterheerdt** [comment]
@waynelapierre are you still having trouble? if not, I'll close this issue.

**Comment by jeroenterheerdt** [comment]
@waynelapierre note that MRO is not supported on Fedora. The list of supported platforms is here: [https://mran.microsoft.com/documents/rro/installation](https://mran.microsoft.com/documents/rro/installation)

For Linux we support:
- Ubuntu 14.04, 16.04, 18.04
- CentOS / Red Hat Enterprise Linux 6.5-6.9, 7.x
- SUSE Linux Enterprise Server 11, 12

**Comment by ismailsunni** [comment]
In case someone arrives here, I manage to install MRO on Fedora. I have the Docker image [here](https://github.com/ismailsunni/dockeRs/blob/master/mro-3.5.3-fedora/Dockerfile).
