### ISSUE TITLE
MRO not found by RStudio

### ISSUE THREAD

**Issue by waynelapierre** [Microsoft/microsoft-r-open#74]
I installed MRO on my Fedora machine, everything works well for me, the issue is that I need to have both CRAN R and MRO to make it work. When I uninstall CRAN R, rstudio cannot find MRO. In addition, when I type R in my terminal, it says that command not found, so I have to reinstall CRAN R to make MRO work.

**Comment by jeroenterheerdt** [comment]
@waynelapierre are you still having trouble? if not, I'll close this issue.
