### ISSUE TITLE
Suggestion: should stop sourcing from www.stats.ox.ac.uk when installing packages

### ISSUE THREAD

**Issue by codetrainee** [Microsoft/microsoft-r-open#83]
Now when installing packages, there will be a warning saying: 
> Warning: unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.5

Actually, the link above is no longer live now. The programm has died since 2016.

**Comment by jeroenterheerdt** [comment]
Hi @richcalaway can we get rid of this? I think we would need to remove it from the repositories list, right? Does it need any replacement?

**Comment by jeroenterheerdt** [comment]
closing this issue now that is has been fixed in release 3.5.2: https://github.com/Microsoft/microsoft-r-open/releases/tag/MRO-3.5.2
