### ISSUE TITLE
version numbers broken on macOS

### ISSUE THREAD

**Issue by core-code** [Microsoft/microsoft-r-open#85]
i've downloaded Version '3.5.1' but when selecting it in the Finder and using 'Get Info' it claims to be Version '3.4.1'

the **CFBundleVersion** and **CFBundleShortVersionString** entries in your **Info.plist** file are broken

<img width="256" alt="screenshot 2018-12-29 at 13 11 21" src="https://user-images.githubusercontent.com/1261954/50538197-18165100-0b6c-11e9-8506-9246a368f102.png">

**Comment by jeroenterheerdt** [comment]
please note that with MRO 3.5.2 going forward we do not support MacOS any longer.
