### ISSUE TITLE
MRO not found after GNU R updated

### ISSUE THREAD

**Issue by waynelapierre** [Microsoft/microsoft-r-open#93]
I have both GNU R 3.5.1 and MRO 3.5.1 installed. When I upgraded GNU R 3.5.1 to 3.5.3, it seemed to be the default R on my Fedora OS. In the terminal, when I type R, the GNU R will show up and RStudio is using GNU R. How can I solve this issue? Can I uninstall GNU R?

**Comment by jeroenterheerdt** [comment]
hope this helps: https://support.rstudio.com/hc/en-us/articles/360002358593-Using-Microsoft-R-Open-MRO-with-RStudio-Server-and-RStudio-Connect
