### ISSUE TITLE
MRO 3.5.3 

### ISSUE THREAD

**Issue by waynelapierre** [Microsoft/microsoft-r-open#98]
On the download page of MRO, it says that MRO 3.5.3 is available on May 10, 2019, but I only see MRO 3.5.2. 
https://mran.microsoft.com/download

**Comment by jeroenterheerdt** [comment]
Yeah, you are right - we did not make it. Should been soon now though.

**Comment by waynelapierre** [comment]
MRO has been really helpful to me. Is there any information about how many R users are using MRO instead of base R? Like number of downloads?

**Comment by jeroenterheerdt** [comment]
No, not publicly.
